### ISSUE TITLE
Make the crown smaller

### ISSUE THREAD

**Issue by dom96** [exercism/nim#107]
The current logo for Nim has the crown a touch too big: 

https://assets.exercism.io/tracks/nim-bordered-green.png

![image](https://user-images.githubusercontent.com/246651/43024492-6aafe6a4-8c66-11e8-8409-0f5ad0c214fc.png)

It would be nice if someone could adjust it to fit inside the borders a bit better (all the other language logos are significantly smaller).

**Comment by amscotti** [comment]
I'm not sure how the images get on https://assets.exercism.io but I'm guessing it's based off of the image found in this repo at https://github.com/exercism/nim/blob/master/img/icon.png

@iHiD What would be the best way for us to update our logo?

**Comment by amscotti** [comment]
Looking more closely at the icon in the repo, I don't think the logo is based off it.

**Comment by iHiD** [comment]
Closing in favour of https://github.com/exercism/website-icons/issues/8 

Website Icons for tracks and exercises are in that repos. The final track icons are pasted together from various bases. It seems like we've make a mistake in the size the crown was exported at. We'll get it sorted as a priority - sorry! :)

**Comment by amscotti** [comment]
@iHiD Thanks for taking a look at this! :)
