### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/nim#13]
_Note: the launch checklist was woefully outdated, since this got created over two years ago, so I deleted it._

If you are interested in leading the charge on getting this track launched, then comment below, and I'll help get this party started based on whatever is current at the time.

We have a launch guide that we'll keep up to date with changes here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by kytrinyx** [comment]
We have enough exercises to launch. @clementi do you know any other enthusiastic Nim folks who could be roped into helping out with this?

In particular we need to make sure that the documentation is correct, and we need people to check in on the website regularly to give people feedback on their code.

**Comment by ChristianBagley** [comment]
As someone who really appreciates Exercism.io as an educational tool, as well as a supporter and newcomer to Nim, I'd love to see the Nim track gain some traction on Exercism.

Do you think it would be beneficial to place some open issues on [BountySource](https://www.bountysource.com/) in an effort to get some attention from the Nim community? 

Also, it may be beneficial to post about this on [Nim forums](http://forum.nim-lang.org/), if it hasn't been mentioned there already (I haven't seen it yet).

**Comment by clementi** [comment]
@ChristianBagley I haven't used BountySource before. I don't know how useful it would be.

I just made a [post](http://forum.nim-lang.org/t/2618) in the Nim forums.

**Comment by kytrinyx** [comment]
Did you hear back from anyone in the Nim forums @clementi?

I'm not familiar with BountySource. From the name it sounds like we'd be paying $$$ for someone to help, and at this point I don't have the resources for that. I'd rather see if we could come up with some way of introducing Exercism's Nim track to people who might already be interested. Are there any meetups that happen? Are there other forums and discussion lists? Slack groups?

**Comment by dom96** [comment]
I would love to see someone maintain this and would do it myself if I had the time.

In the meantime, I posted a link to this on our IRC channel, maybe somebody will be interested in helping out.

**Comment by clementi** [comment]
@kytrinyx This is all: http://forum.nim-lang.org/t/2618#16200

**Comment by kytrinyx** [comment]
Thanks @dom96—fingers crossed :)

Thanks @clementi. It's interesting that people occasionally find the name off-putting.

**Comment by Yardanico** [comment]
So currently Nim has 25 exercises, is that enough? And I think some Nim developers will be happy to join mentor team (I've passed a link in our chat)

**Comment by amscotti** [comment]
@Yardanico I think 25 is fine based on looking at numbers for other languages that are launch on Exercism site, CoffeeScript has 21, Crystal has 24, and D has 18. So, I think 25 is fine and over time we will get more.

I think what we are missing is the write up for learning Nim for issue https://github.com/exercism/nim/issues/34

I'm planning on writing up something for learning Nim this week. Beside that, I think we are about ready to launch this track.

**Comment by kytrinyx** [comment]
25 is more than enough! This is very exciting!! 🌷

**Comment by kytrinyx** [comment]
Oh! And you can see what the Nim track will look like when we launch the v2 website (hopefully within the next couple of months). http://v2.exercism.io/tracks/nim

**Comment by amscotti** [comment]
![nim exercism 2018-06-06 08-55-38](https://user-images.githubusercontent.com/598958/41039426-64bda294-6967-11e8-9b27-be76d7d83ee4.png)

@kytrinyx Where does the description for the track get pulled from?

**Comment by kaushalmodi** [comment]
Where can I open issues/submit PR's for incomplete information for the user.. see this Nim task as example: http://exercism.io/submissions/239fd14892bf4a8e9594c4218bbbee67.

**Comment by amscotti** [comment]
@kaushalmodi You can create a new issue or PR in this repo. Sounds like Word Count could use a hint to help people to know to use the `critbits` library.

**Comment by Yardanico** [comment]
@kaushalmodi https://v2.exercism.io/tracks/nim is already https

**Comment by amscotti** [comment]
I just merged an PR to set `active` to `true` in the config.json file, unless something else needs to happen I think we are launched!  🎉
