### ISSUE TITLE
Override probot/stale defaults, if necessary

### ISSUE THREAD

**Issue by kytrinyx** [exercism/nim#37]
Per the discussion in https://github.com/exercism/discussions/issues/128 we
will be installing the probot/stale integration on the Exercism organization on
April 10th, 2017.

By default, probot will comment on issues that are older than 60 days, warning
that they are stale. If there is no movement in 7 days, the bot will close the issue.
By default, anything with the labels `security` or `pinned` will not be closed by
probot.

If you wish to override these settings, create a .github/stale.yml file as described
in https://github.com/probot/stale#usage, and make sure that it is merged
before April 10th.

If the defaults are fine for this repository, then there is nothing further to do.
You may close this issue.

**Comment by kytrinyx** [comment]
I made a mistake.

This was not explicitly documented in the README, but probot/stale **requires the presence of a .github/stale.yml** file.

If you want the default behavior, you need to add an empty .github/stale.yml file to this repo, otherwise the bot will not be active.

**Comment by amscotti** [comment]
I think this is a good idea, I have added PR for adding the `stale.yml` file.

**Comment by kytrinyx** [comment]
Now that I've been living with this for a while, I've found that it's less useful than I originally expected, in particular for repositories where there's not a whole lot of activity (e.g. if there were hundreds of issues every week, then having a bot to automatically close them regularly is good).

The most annoying thing is where we have 10 open issues, and maybe 2 people have contributed in the past 6 months... and we hit the threshold and 8 of the issues get closed because they're stale, even though it's not an overwhelming number of issues to comb through.

**Comment by amscotti** [comment]
Yeah, I can see your point and maybe for this track it's not going to be an issue. It's easy enough to add if we want it later on. Let's close this issue and I'll close my PR. :)

**Comment by kytrinyx** [comment]
Sounds good!
