### ISSUE TITLE
Mistake in Triangle tests

### ISSUE THREAD

**Issue by k0pernicus** [exercism/nim#50]
In the triangle exercise, you note that "_...the sum of the lengths of any two sides must be greater than or equal to the length of the third side._".
In the test "_triangles violating triangle inequality are illegal 2_", the expected answer is to raise `ValueError` for the test `kind(2,4,2)`.

I think the answer for this test must be **Equilateral**, and not an error, because `2 + 4 > 2`, `4 + 2 > 2`, and `2 + 2 == 4`.

**Comment by amscotti** [comment]
Hi @k0pernicus,

Thanks for pointing out this issue, doing some looking around and checking the [problem specifications](https://github.com/exercism/problem-specifications/blob/master/exercises/triangle/canonical-data.json) it seems like we shouldn't be testing for a triangle with length of 2,4,2. I believe this is a degenerate triangle and has zero area. Using the "Triangle inequality" from Wikipedia, the mathematical expression should be, `a + b > c, b + c > a, and c + a > b` and 2,4,2 fails for `2 + 2 > 4` if I'm understanding this correctly.

So, this should error based on my understanding of the "Triangle inequality", but it shouldn't be part of the test from what the `canonical-data.json` said. It also maybe a good idea to update this exercise to better match the test cases in `canonical-data.json`.

Let me know if this all makes sense to you or if I missed some detail. Thanks!
