### ISSUE TITLE
"Bob" problem - missing test case

### ISSUE THREAD

**Issue by kaushalmodi** [exercism/nim#78]
The test suite is missing a test for this spec:

> He answers 'Calm down, I know what I'm doing!' if you yell a question at him.

**Comment by amscotti** [comment]
@kaushalmodi Thanks for reporting this, you are right! From the test at https://github.com/exercism/nim/blob/master/exercises/bob/bob_test.nim#L31 this should be returning `"Calm down, I know what I'm doing!"` based on the canonical data at https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json#L70

I'll take a look at fixing this today.

**Comment by kaushalmodi** [comment]
Yeah.. earlier I had `isQuestion` check at a higher precedence, but then did this just to make the test pass 
 
```nim
    if isShouting:
      return "Whoa, chill out!"
    elif isQuestion:
      if isShouting:  # this if condition will never be reached!
        return "Calm down, I know what I'm doing!"
```

http://exercism.io/submissions/eb9e4ee5de61487f8756edade426ba72
