### ISSUE TITLE
 React is way to hard for its current position in the exercise list

### ISSUE THREAD

**Issue by shybyte** [exercism/nim#83]
The "react" exercise comes currently after the triangle exercise and before the binary exercise. 
In my opinion, the "react" exercise is the most difficult exercise of all existing exercises.  It's not only hard as exercise itself but requires probably also a lot of advanced Nim knowledge.
There is a reason, why it's in other tracks like http://exercism.io/languages/rust/exercises at the very end. I mean, due to no borrow checker in Nim, it might be easier than in Rust, but probably it's still the most difficult exercise.

**Comment by amscotti** [comment]
@shybyte thanks for the feedback, I agree with you on this! From the command line you're able to skip it and move on to another exercise but yes, the order for this exercise is very much out of place for someone learning Nim.

I'll make a task for myself to work on adding some kind of order to all our exercises.

Thanks again for your feedback
